# Generated native capability expansion: read-only diagnostics and explicit Android navigation.
from __future__ import annotations
import agent

def _intent(action):
    def fn(args):
        return agent.run(["am", "start", "-a", action])
    return fn

def _cmd(command):
    def fn(args):
        return agent.shell(command)
    return fn

FEATURES = []

FEATURES.append("android.settings.accessibility"); agent.SKILLS["android.settings.accessibility"]=("Open the Android accessibility settings page.", _intent("android.settings.ACCESSIBILITY_SETTINGS"))
FEATURES.append("android.settings.accounts"); agent.SKILLS["android.settings.accounts"]=("Open the Android accounts settings page.", _intent("android.settings.SYNC_SETTINGS"))
FEATURES.append("android.settings.airplane_mode"); agent.SKILLS["android.settings.airplane_mode"]=("Open the Android airplane_mode settings page.", _intent("android.settings.AIRPLANE_MODE_SETTINGS"))
FEATURES.append("android.settings.app_details"); agent.SKILLS["android.settings.app_details"]=("Open the Android app_details settings page.", _intent("android.settings.APPLICATION_DETAILS_SETTINGS"))
FEATURES.append("android.settings.app_notifications"); agent.SKILLS["android.settings.app_notifications"]=("Open the Android app_notifications settings page.", _intent("android.settings.APP_NOTIFICATION_SETTINGS"))
FEATURES.append("android.settings.battery"); agent.SKILLS["android.settings.battery"]=("Open the Android battery settings page.", _intent("android.settings.BATTERY_SAVER_SETTINGS"))
FEATURES.append("android.settings.bluetooth"); agent.SKILLS["android.settings.bluetooth"]=("Open the Android bluetooth settings page.", _intent("android.settings.BLUETOOTH_SETTINGS"))
FEATURES.append("android.settings.data_usage"); agent.SKILLS["android.settings.data_usage"]=("Open the Android data_usage settings page.", _intent("android.settings.DATA_USAGE_SETTINGS"))
FEATURES.append("android.settings.date_time"); agent.SKILLS["android.settings.date_time"]=("Open the Android date_time settings page.", _intent("android.settings.DATE_SETTINGS"))
FEATURES.append("android.settings.display"); agent.SKILLS["android.settings.display"]=("Open the Android display settings page.", _intent("android.settings.DISPLAY_SETTINGS"))
FEATURES.append("android.settings.home"); agent.SKILLS["android.settings.home"]=("Open the Android home settings page.", _intent("android.settings.HOME_SETTINGS"))
FEATURES.append("android.settings.input"); agent.SKILLS["android.settings.input"]=("Open the Android input settings page.", _intent("android.settings.INPUT_METHOD_SETTINGS"))
FEATURES.append("android.settings.language"); agent.SKILLS["android.settings.language"]=("Open the Android language settings page.", _intent("android.settings.LOCALE_SETTINGS"))
FEATURES.append("android.settings.location"); agent.SKILLS["android.settings.location"]=("Open the Android location settings page.", _intent("android.settings.LOCATION_SOURCE_SETTINGS"))
FEATURES.append("android.settings.manage_apps"); agent.SKILLS["android.settings.manage_apps"]=("Open the Android manage_apps settings page.", _intent("android.settings.MANAGE_APPLICATIONS_SETTINGS"))
FEATURES.append("android.settings.nfc"); agent.SKILLS["android.settings.nfc"]=("Open the Android nfc settings page.", _intent("android.settings.NFC_SETTINGS"))
FEATURES.append("android.settings.notification"); agent.SKILLS["android.settings.notification"]=("Open the Android notification settings page.", _intent("android.settings.NOTIFICATION_SETTINGS"))
FEATURES.append("android.settings.print"); agent.SKILLS["android.settings.print"]=("Open the Android print settings page.", _intent("android.settings.ACTION_PRINT_SETTINGS"))
FEATURES.append("android.settings.privacy"); agent.SKILLS["android.settings.privacy"]=("Open the Android privacy settings page.", _intent("android.settings.PRIVACY_SETTINGS"))
FEATURES.append("android.settings.security"); agent.SKILLS["android.settings.security"]=("Open the Android security settings page.", _intent("android.settings.SECURITY_SETTINGS"))
FEATURES.append("android.settings.sound"); agent.SKILLS["android.settings.sound"]=("Open the Android sound settings page.", _intent("android.settings.SOUND_SETTINGS"))
FEATURES.append("android.settings.storage"); agent.SKILLS["android.settings.storage"]=("Open the Android storage settings page.", _intent("android.settings.INTERNAL_STORAGE_SETTINGS"))
FEATURES.append("android.settings.sync"); agent.SKILLS["android.settings.sync"]=("Open the Android sync settings page.", _intent("android.settings.SYNC_SETTINGS"))
FEATURES.append("android.settings.usage"); agent.SKILLS["android.settings.usage"]=("Open the Android usage settings page.", _intent("android.settings.USAGE_ACCESS_SETTINGS"))
FEATURES.append("android.settings.vpn"); agent.SKILLS["android.settings.vpn"]=("Open the Android vpn settings page.", _intent("android.settings.VPN_SETTINGS"))
FEATURES.append("android.settings.wifi"); agent.SKILLS["android.settings.wifi"]=("Open the Android wifi settings page.", _intent("android.settings.WIFI_SETTINGS"))
FEATURES.append("android.settings.developer"); agent.SKILLS["android.settings.developer"]=("Open the Android developer settings page.", _intent("android.settings.APPLICATION_DEVELOPMENT_SETTINGS"))
FEATURES.append("android.settings.notification_policy"); agent.SKILLS["android.settings.notification_policy"]=("Open the Android notification_policy settings page.", _intent("android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS"))
FEATURES.append("android.settings.accessibility_service"); agent.SKILLS["android.settings.accessibility_service"]=("Open the Android accessibility_service settings page.", _intent("android.settings.ACCESSIBILITY_SETTINGS"))
FEATURES.append("android.settings.default_apps"); agent.SKILLS["android.settings.default_apps"]=("Open the Android default_apps settings page.", _intent("android.settings.MANAGE_DEFAULT_APPS_SETTINGS"))
FEATURES.append("device.uptime"); agent.SKILLS["device.uptime"]=("Read device.uptime from the Android device.", _cmd("cat /proc/uptime"))
FEATURES.append("device.kernel"); agent.SKILLS["device.kernel"]=("Read device.kernel from the Android device.", _cmd("uname -a"))
FEATURES.append("device.cpu_model"); agent.SKILLS["device.cpu_model"]=("Read device.cpu_model from the Android device.", _cmd("cat /proc/cpuinfo"))
FEATURES.append("device.memory"); agent.SKILLS["device.memory"]=("Read device.memory from the Android device.", _cmd("cat /proc/meminfo"))
FEATURES.append("device.load"); agent.SKILLS["device.load"]=("Read device.load from the Android device.", _cmd("cat /proc/loadavg"))
FEATURES.append("device.mounts"); agent.SKILLS["device.mounts"]=("Read device.mounts from the Android device.", _cmd("cat /proc/mounts"))
FEATURES.append("device.disk"); agent.SKILLS["device.disk"]=("Read device.disk from the Android device.", _cmd("df -h"))
FEATURES.append("device.storage_data"); agent.SKILLS["device.storage_data"]=("Read device.storage_data from the Android device.", _cmd("df -h /data"))
FEATURES.append("device.storage_sdcard"); agent.SKILLS["device.storage_sdcard"]=("Read device.storage_sdcard from the Android device.", _cmd("df -h /sdcard"))
FEATURES.append("device.properties"); agent.SKILLS["device.properties"]=("Read device.properties from the Android device.", _cmd("getprop"))
FEATURES.append("device.locale"); agent.SKILLS["device.locale"]=("Read device.locale from the Android device.", _cmd("getprop persist.sys.locale"))
FEATURES.append("device.timezone"); agent.SKILLS["device.timezone"]=("Read device.timezone from the Android device.", _cmd("getprop persist.sys.timezone"))
FEATURES.append("device.serial"); agent.SKILLS["device.serial"]=("Read device.serial from the Android device.", _cmd("getprop ro.serialno"))
FEATURES.append("device.manufacturer"); agent.SKILLS["device.manufacturer"]=("Read device.manufacturer from the Android device.", _cmd("getprop ro.product.manufacturer"))
FEATURES.append("device.brand"); agent.SKILLS["device.brand"]=("Read device.brand from the Android device.", _cmd("getprop ro.product.brand"))
FEATURES.append("device.model"); agent.SKILLS["device.model"]=("Read device.model from the Android device.", _cmd("getprop ro.product.model"))
FEATURES.append("device.product"); agent.SKILLS["device.product"]=("Read device.product from the Android device.", _cmd("getprop ro.product.name"))
FEATURES.append("device.board"); agent.SKILLS["device.board"]=("Read device.board from the Android device.", _cmd("getprop ro.product.board"))
FEATURES.append("device.sdk"); agent.SKILLS["device.sdk"]=("Read device.sdk from the Android device.", _cmd("getprop ro.build.version.sdk"))
FEATURES.append("device.security_patch"); agent.SKILLS["device.security_patch"]=("Read device.security_patch from the Android device.", _cmd("getprop ro.build.version.security_patch"))
FEATURES.append("device.build_fingerprint"); agent.SKILLS["device.build_fingerprint"]=("Read device.build_fingerprint from the Android device.", _cmd("getprop ro.build.fingerprint"))
FEATURES.append("device.bootloader"); agent.SKILLS["device.bootloader"]=("Read device.bootloader from the Android device.", _cmd("getprop ro.bootloader"))
FEATURES.append("device.hardware"); agent.SKILLS["device.hardware"]=("Read device.hardware from the Android device.", _cmd("getprop ro.hardware"))
FEATURES.append("device.abi"); agent.SKILLS["device.abi"]=("Read device.abi from the Android device.", _cmd("getprop ro.product.cpu.abilist"))
FEATURES.append("device.thermal"); agent.SKILLS["device.thermal"]=("Read device.thermal from the Android device.", _cmd("dumpsys thermalservice"))
FEATURES.append("network.interfaces"); agent.SKILLS["network.interfaces"]=("Read network.interfaces from the Android device.", _cmd("ip addr"))
FEATURES.append("network.routes"); agent.SKILLS["network.routes"]=("Read network.routes from the Android device.", _cmd("ip route"))
FEATURES.append("network.dns"); agent.SKILLS["network.dns"]=("Read network.dns from the Android device.", _cmd("getprop | grep -E 'dns|net\\.dns'"))
FEATURES.append("network.proxy"); agent.SKILLS["network.proxy"]=("Read network.proxy from the Android device.", _cmd("settings get global http_proxy"))
FEATURES.append("network.mobile"); agent.SKILLS["network.mobile"]=("Read network.mobile from the Android device.", _cmd("getprop | grep -E 'gsm|telephony'"))
FEATURES.append("network.wifi_state"); agent.SKILLS["network.wifi_state"]=("Read network.wifi_state from the Android device.", _cmd("dumpsys wifi | head -120"))
FEATURES.append("network.connectivity"); agent.SKILLS["network.connectivity"]=("Read network.connectivity from the Android device.", _cmd("dumpsys connectivity | head -160"))
FEATURES.append("network.active"); agent.SKILLS["network.active"]=("Read network.active from the Android device.", _cmd("dumpsys connectivity | grep -E 'NetworkAgentInfo|NetworkInfo'"))
FEATURES.append("network.ipv4"); agent.SKILLS["network.ipv4"]=("Read network.ipv4 from the Android device.", _cmd("ip -4 addr"))
FEATURES.append("network.ipv6"); agent.SKILLS["network.ipv6"]=("Read network.ipv6 from the Android device.", _cmd("ip -6 addr"))
FEATURES.append("network.neighbors"); agent.SKILLS["network.neighbors"]=("Read network.neighbors from the Android device.", _cmd("ip neigh"))
FEATURES.append("network.tcp"); agent.SKILLS["network.tcp"]=("Read network.tcp from the Android device.", _cmd("cat /proc/net/tcp"))
FEATURES.append("network.udp"); agent.SKILLS["network.udp"]=("Read network.udp from the Android device.", _cmd("cat /proc/net/udp"))
FEATURES.append("network.sockets"); agent.SKILLS["network.sockets"]=("Read network.sockets from the Android device.", _cmd("cat /proc/net/sockstat"))
FEATURES.append("network.hosts"); agent.SKILLS["network.hosts"]=("Read network.hosts from the Android device.", _cmd("cat /system/etc/hosts"))
FEATURES.append("network.ethernet"); agent.SKILLS["network.ethernet"]=("Read network.ethernet from the Android device.", _cmd("dumpsys ethernet"))
FEATURES.append("network.vpn_state"); agent.SKILLS["network.vpn_state"]=("Read network.vpn_state from the Android device.", _cmd("dumpsys connectivity | grep -i vpn"))
FEATURES.append("network.wifi_config"); agent.SKILLS["network.wifi_config"]=("Read network.wifi_config from the Android device.", _cmd("dumpsys wifi | grep -E 'SSID|BSSID|mNetworkInfo' | head -80"))
FEATURES.append("network.radio"); agent.SKILLS["network.radio"]=("Read network.radio from the Android device.", _cmd("getprop | grep -E 'radio|ril'"))
FEATURES.append("network.ping_gateway"); agent.SKILLS["network.ping_gateway"]=("Read network.ping_gateway from the Android device.", _cmd("ip route"))
FEATURES.append("files.cwd"); agent.SKILLS["files.cwd"]=("Read files.cwd from the Android device.", _cmd("pwd"))
FEATURES.append("files.root_listing"); agent.SKILLS["files.root_listing"]=("Read files.root_listing from the Android device.", _cmd("ls -la /"))
FEATURES.append("files.data_listing"); agent.SKILLS["files.data_listing"]=("Read files.data_listing from the Android device.", _cmd("ls -la /data"))
FEATURES.append("files.sdcard_listing"); agent.SKILLS["files.sdcard_listing"]=("Read files.sdcard_listing from the Android device.", _cmd("ls -la /sdcard"))
FEATURES.append("files.agent_listing"); agent.SKILLS["files.agent_listing"]=("Read files.agent_listing from the Android device.", _cmd("ls -la ~/.jarvis-agent"))
FEATURES.append("files.tmp_listing"); agent.SKILLS["files.tmp_listing"]=("Read files.tmp_listing from the Android device.", _cmd("ls -la /data/local/tmp"))
FEATURES.append("files.proc_listing"); agent.SKILLS["files.proc_listing"]=("Read files.proc_listing from the Android device.", _cmd("ls -la /proc | head -100"))
FEATURES.append("files.dev_listing"); agent.SKILLS["files.dev_listing"]=("Read files.dev_listing from the Android device.", _cmd("ls -la /dev | head -100"))
FEATURES.append("files.sys_listing"); agent.SKILLS["files.sys_listing"]=("Read files.sys_listing from the Android device.", _cmd("ls -la /sys | head -100"))
FEATURES.append("files.storage_usage"); agent.SKILLS["files.storage_usage"]=("Read files.storage_usage from the Android device.", _cmd("du -sh /sdcard 2>/dev/null"))
FEATURES.append("files.data_usage"); agent.SKILLS["files.data_usage"]=("Read files.data_usage from the Android device.", _cmd("du -sh /data 2>/dev/null"))
FEATURES.append("files.agent_usage"); agent.SKILLS["files.agent_usage"]=("Read files.agent_usage from the Android device.", _cmd("du -sh ~/.jarvis-agent 2>/dev/null"))
FEATURES.append("files.recent"); agent.SKILLS["files.recent"]=("Read files.recent from the Android device.", _cmd("find /sdcard -type f -mmin -60 -print 2>/dev/null | head -100"))
FEATURES.append("files.large"); agent.SKILLS["files.large"]=("Read files.large from the Android device.", _cmd("find /sdcard -type f -size +50M -print 2>/dev/null | head -100"))
FEATURES.append("files.images"); agent.SKILLS["files.images"]=("Read files.images from the Android device.", _cmd("find /sdcard -type f -iname '*.jpg' -o -iname '*.png' -o -iname '*.webp' 2>/dev/null | head -100"))
FEATURES.append("files.videos"); agent.SKILLS["files.videos"]=("Read files.videos from the Android device.", _cmd("find /sdcard -type f -iname '*.mp4' -o -iname '*.mkv' -o -iname '*.webm' 2>/dev/null | head -100"))
FEATURES.append("files.audio"); agent.SKILLS["files.audio"]=("Read files.audio from the Android device.", _cmd("find /sdcard -type f -iname '*.mp3' -o -iname '*.m4a' -o -iname '*.wav' 2>/dev/null | head -100"))
FEATURES.append("files.documents"); agent.SKILLS["files.documents"]=("Read files.documents from the Android device.", _cmd("find /sdcard -type f -iname '*.pdf' -o -iname '*.docx' -o -iname '*.txt' 2>/dev/null | head -100"))
FEATURES.append("files.downloads"); agent.SKILLS["files.downloads"]=("Read files.downloads from the Android device.", _cmd("ls -lat /sdcard/Download 2>/dev/null | head -100"))
FEATURES.append("files.dcim"); agent.SKILLS["files.dcim"]=("Read files.dcim from the Android device.", _cmd("ls -lat /sdcard/DCIM 2>/dev/null | head -100"))
FEATURES.append("files.pictures"); agent.SKILLS["files.pictures"]=("Read files.pictures from the Android device.", _cmd("ls -lat /sdcard/Pictures 2>/dev/null | head -100"))
FEATURES.append("files.movies"); agent.SKILLS["files.movies"]=("Read files.movies from the Android device.", _cmd("ls -lat /sdcard/Movies 2>/dev/null | head -100"))
FEATURES.append("files.music"); agent.SKILLS["files.music"]=("Read files.music from the Android device.", _cmd("ls -lat /sdcard/Music 2>/dev/null | head -100"))
FEATURES.append("files.documents_listing"); agent.SKILLS["files.documents_listing"]=("Read files.documents_listing from the Android device.", _cmd("ls -lat /sdcard/Documents 2>/dev/null | head -100"))
FEATURES.append("files.checksum"); agent.SKILLS["files.checksum"]=("Read files.checksum from the Android device.", _cmd("sha256sum ~/.jarvis-agent/catalog.json 2>/dev/null"))
FEATURES.append("files.agent_config"); agent.SKILLS["files.agent_config"]=("Read files.agent_config from the Android device.", _cmd("cat ~/.jarvis-agent/catalog.json 2>/dev/null"))
FEATURES.append("apps.default_launcher"); agent.SKILLS["apps.default_launcher"]=("Read apps.default_launcher from the Android device.", _cmd("cmd package resolve-activity --brief -a android.intent.action.MAIN -c android.intent.category.HOME"))
FEATURES.append("apps.default_browser"); agent.SKILLS["apps.default_browser"]=("Read apps.default_browser from the Android device.", _cmd("cmd package resolve-activity --brief -a android.intent.action.VIEW -d https://example.com"))
FEATURES.append("apps.package_count"); agent.SKILLS["apps.package_count"]=("Read apps.package_count from the Android device.", _cmd("cmd package list packages | wc -l"))
FEATURES.append("apps.system_count"); agent.SKILLS["apps.system_count"]=("Read apps.system_count from the Android device.", _cmd("cmd package list packages -s | wc -l"))
FEATURES.append("apps.third_party_count"); agent.SKILLS["apps.third_party_count"]=("Read apps.third_party_count from the Android device.", _cmd("cmd package list packages -3 | wc -l"))
FEATURES.append("apps.enabled_count"); agent.SKILLS["apps.enabled_count"]=("Read apps.enabled_count from the Android device.", _cmd("cmd package list packages -e | wc -l"))
FEATURES.append("apps.disabled_count"); agent.SKILLS["apps.disabled_count"]=("Read apps.disabled_count from the Android device.", _cmd("cmd package list packages -d | wc -l"))
FEATURES.append("apps.permissions"); agent.SKILLS["apps.permissions"]=("Read apps.permissions from the Android device.", _cmd("pm list permissions -g"))
FEATURES.append("apps.features"); agent.SKILLS["apps.features"]=("Read apps.features from the Android device.", _cmd("pm list features"))
FEATURES.append("apps.services"); agent.SKILLS["apps.services"]=("Read apps.services from the Android device.", _cmd("dumpsys activity services | head -160"))
FEATURES.append("apps.activities"); agent.SKILLS["apps.activities"]=("Read apps.activities from the Android device.", _cmd("dumpsys activity activities | head -160"))
FEATURES.append("apps.tasks"); agent.SKILLS["apps.tasks"]=("Read apps.tasks from the Android device.", _cmd("dumpsys activity activities | grep -E 'Task|mResumedActivity' | head -80"))
FEATURES.append("apps.current"); agent.SKILLS["apps.current"]=("Read apps.current from the Android device.", _cmd("dumpsys window | grep -E 'mCurrentFocus|mFocusedApp' | head -20"))
FEATURES.append("apps.top_process"); agent.SKILLS["apps.top_process"]=("Read apps.top_process from the Android device.", _cmd("dumpsys activity top | head -120"))
FEATURES.append("apps.package_sessions"); agent.SKILLS["apps.package_sessions"]=("Read apps.package_sessions from the Android device.", _cmd("pm list packages -f | head -100"))
FEATURES.append("apps.providers"); agent.SKILLS["apps.providers"]=("Read apps.providers from the Android device.", _cmd("dumpsys package providers | head -120"))
FEATURES.append("apps.receivers"); agent.SKILLS["apps.receivers"]=("Read apps.receivers from the Android device.", _cmd("dumpsys package receivers | head -120"))
FEATURES.append("apps.shared_users"); agent.SKILLS["apps.shared_users"]=("Read apps.shared_users from the Android device.", _cmd("pm list users"))
FEATURES.append("apps.staged_sessions"); agent.SKILLS["apps.staged_sessions"]=("Read apps.staged_sessions from the Android device.", _cmd("pm list packages --apex-only 2>/dev/null"))
FEATURES.append("apps.versioned_packages"); agent.SKILLS["apps.versioned_packages"]=("Read apps.versioned_packages from the Android device.", _cmd("pm list packages --show-versioncode | head -100"))
FEATURES.append("ui.window"); agent.SKILLS["ui.window"]=("Read ui.window from the Android device.", _cmd("dumpsys window | grep -E 'mCurrentFocus|mFocusedApp|mInputMethodTarget'"))
FEATURES.append("ui.display"); agent.SKILLS["ui.display"]=("Read ui.display from the Android device.", _cmd("wm size; wm density"))
FEATURES.append("ui.rotation"); agent.SKILLS["ui.rotation"]=("Read ui.rotation from the Android device.", _cmd("settings get system accelerometer_rotation; settings get system user_rotation"))
FEATURES.append("ui.statusbar"); agent.SKILLS["ui.statusbar"]=("Read ui.statusbar from the Android device.", _cmd("dumpsys statusbar | head -100"))
FEATURES.append("ui.input"); agent.SKILLS["ui.input"]=("Read ui.input from the Android device.", _cmd("dumpsys input | head -140"))
FEATURES.append("ui.power"); agent.SKILLS["ui.power"]=("Read ui.power from the Android device.", _cmd("dumpsys power | head -140"))
FEATURES.append("ui.audio"); agent.SKILLS["ui.audio"]=("Read ui.audio from the Android device.", _cmd("dumpsys audio | head -160"))
FEATURES.append("ui.media_session"); agent.SKILLS["ui.media_session"]=("Read ui.media_session from the Android device.", _cmd("dumpsys media_session | head -140"))
FEATURES.append("ui.notifications"); agent.SKILLS["ui.notifications"]=("Read ui.notifications from the Android device.", _cmd("dumpsys notification --noredact | head -160"))
FEATURES.append("ui.jobs"); agent.SKILLS["ui.jobs"]=("Read ui.jobs from the Android device.", _cmd("dumpsys jobscheduler | head -160"))
FEATURES.append("ui.alarms"); agent.SKILLS["ui.alarms"]=("Read ui.alarms from the Android device.", _cmd("dumpsys alarm | head -160"))
FEATURES.append("ui.battery"); agent.SKILLS["ui.battery"]=("Read ui.battery from the Android device.", _cmd("dumpsys battery"))
FEATURES.append("ui.package_manager"); agent.SKILLS["ui.package_manager"]=("Read ui.package_manager from the Android device.", _cmd("dumpsys package | head -100"))
FEATURES.append("ui.activity_manager"); agent.SKILLS["ui.activity_manager"]=("Read ui.activity_manager from the Android device.", _cmd("dumpsys activity | head -100"))
FEATURES.append("ui.gfx"); agent.SKILLS["ui.gfx"]=("Read ui.gfx from the Android device.", _cmd("dumpsys gfxinfo | head -160"))
FEATURES.append("ui.surfaceflinger"); agent.SKILLS["ui.surfaceflinger"]=("Read ui.surfaceflinger from the Android device.", _cmd("dumpsys SurfaceFlinger --list | head -120"))
FEATURES.append("ui.window_stack"); agent.SKILLS["ui.window_stack"]=("Read ui.window_stack from the Android device.", _cmd("dumpsys activity containers | head -120"))
FEATURES.append("ui.keyguard"); agent.SKILLS["ui.keyguard"]=("Read ui.keyguard from the Android device.", _cmd("dumpsys window policy | grep -E 'isStatusBarKeyguard|isKeyguardShowing'"))
FEATURES.append("ui.device_policy"); agent.SKILLS["ui.device_policy"]=("Read ui.device_policy from the Android device.", _cmd("dumpsys device_policy | head -140"))
FEATURES.append("ui.accessibility"); agent.SKILLS["ui.accessibility"]=("Read ui.accessibility from the Android device.", _cmd("dumpsys accessibility | head -120"))
FEATURES.append("ui.clipboard"); agent.SKILLS["ui.clipboard"]=("Read ui.clipboard from the Android device.", _cmd("cmd clipboard get 2>/dev/null"))

assert len(FEATURES) == 142
