package com.pr4nav.jarvis.companion

import android.app.AlarmManager
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import androidx.core.app.NotificationCompat
import com.pr4nav.jarvis.AgentActivity
import com.pr4nav.jarvis.R
import com.pr4nav.jarvis.memory.JarvisMemoryStore
import com.pr4nav.jarvis.memory.JarvisPersonaStore
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.util.Calendar
import java.util.concurrent.Executors

/**
 * Proactive companion engine — Jarvis initiates conversations like a human friend.
 *
 * NOT cron-based. Uses randomised AlarmManager windows + context signals to decide
 * WHEN and WHETHER to send a message. A dice roll (30% chance) + human-hour guard
 * prevents spam. At most 2 proactive messages per day.
 *
 * Message content is generated by the LLM using persona + memory context.
 */
object JarvisProactiveEngine {

    private const val TAG = "JarvisProactiveEngine"
    private const val PREFS = "jarvis_proactive"
    private const val CHANNEL_ID = "jarvis_companion"
    private const val NOTIF_ID = 7742

    // Keys
    private const val KEY_ENABLED = "proactive_enabled"
    private const val KEY_MSGS_TODAY = "msgs_today"
    private const val KEY_TODAY_DATE = "today_date"
    private const val KEY_LAST_MSG_MS = "last_msg_ms"

    private val executor = Executors.newSingleThreadExecutor()

    // ── Public API ────────────────────────────────────────────────────────────

    fun isEnabled(context: Context): Boolean =
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .getBoolean(KEY_ENABLED, false)

    fun setEnabled(context: Context, enabled: Boolean) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().putBoolean(KEY_ENABLED, enabled).apply()
        if (enabled) scheduleNext(context) else cancel(context)
    }

    /** Schedule the next proactive wake-up. Called after each message and on boot. */
    fun scheduleNext(context: Context) {
        if (!isEnabled(context)) return
        val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        val pi = pendingIntent(context)

        // Random window: 2–5 hours from now
        val delayMs = (2 * 60 + (0..180).random()) * 60_000L
        val triggerAt = System.currentTimeMillis() + delayMs

        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S && am.canScheduleExactAlarms()) {
                am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
            } else {
                am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pi)
            }
            Log.d(TAG, "Next proactive check in ${delayMs / 60_000}min")
        } catch (e: Exception) {
            Log.w(TAG, "Could not schedule alarm: ${e.message}")
        }
    }

    fun cancel(context: Context) {
        val am = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
        am.cancel(pendingIntent(context))
    }

    // ── Core logic (called by BroadcastReceiver) ──────────────────────────────

    fun onAlarmFired(context: Context) {
        if (!isEnabled(context)) return

        // Human-hours guard: never interrupt between 2am and 11am (respects nocturnal schedule)
        val hour = Calendar.getInstance().get(Calendar.HOUR_OF_DAY)
        if (hour in 2..10) {
            Log.d(TAG, "Skipping: sleep hours ($hour:00)")
            scheduleNext(context)
            return
        }

        // Daily cap: max 2 messages per day
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val today = java.text.SimpleDateFormat("yyyy-MM-dd", java.util.Locale.US).format(java.util.Date())
        val savedDate = prefs.getString(KEY_TODAY_DATE, "")
        val msgsToday = if (savedDate == today) prefs.getInt(KEY_MSGS_TODAY, 0) else 0
        if (msgsToday >= 2) {
            Log.d(TAG, "Daily cap reached ($msgsToday msgs). Scheduling for tomorrow.")
            scheduleNext(context)
            return
        }

        // Minimum 3h gap between messages
        val lastMsgMs = prefs.getLong(KEY_LAST_MSG_MS, 0L)
        if (System.currentTimeMillis() - lastMsgMs < 3 * 60 * 60_000L) {
            scheduleNext(context)
            return
        }

        // Dice roll: 30% chance to actually send
        if ((1..10).random() > 3) {
            Log.d(TAG, "Dice roll miss. Rescheduling.")
            scheduleNext(context)
            return
        }

        // Generate and send
        executor.execute {
            try {
                val msg = generateMessage(context)
                if (msg.isNotBlank()) {
                    sendNotification(context, msg)
                    // Record
                    prefs.edit()
                        .putString(KEY_TODAY_DATE, today)
                        .putInt(KEY_MSGS_TODAY, msgsToday + 1)
                        .putLong(KEY_LAST_MSG_MS, System.currentTimeMillis())
                        .apply()
                }
            } catch (e: Exception) {
                Log.w(TAG, "Message generation failed: ${e.message}")
            }
            scheduleNext(context)
        }
    }

    // ── Message generation ────────────────────────────────────────────────────

    private fun generateMessage(context: Context): String {
        val persona = JarvisPersonaStore.buildPersonaBlock(context)
        val memories = try {
            JarvisMemoryStore.getAll(context).take(5).joinToString("; ") { "${it.key}: ${it.value}" }
        } catch (_: Exception) { "" }

        val hour = Calendar.getInstance().get(Calendar.HOUR_OF_DAY)
        val timeOfDay = when (hour) {
            in 11..14 -> "afternoon"
            in 15..19 -> "evening"
            in 20..23 -> "night"
            else -> "late night"
        }

        val prompt = buildString {
            appendLine("You are JARVIS, a close AI companion. Send ONE short, natural, human-sounding check-in message (1-2 sentences max).")
            appendLine("Current time: $timeOfDay. Do NOT start with 'Hi' or 'Hello'. Be casual, terse, genuine.")
            appendLine("Examples: 'gm', 'yo what you up to', 'any progress on [goal]?', 'haven't heard from you in a bit'")
            appendLine("Context about the user:")
            if (persona.isNotBlank()) appendLine(persona)
            if (memories.isNotBlank()) appendLine("Memories: $memories")
            appendLine("\nSend ONLY the message text. No quotes. No explanation.")
        }

        return callKiraForCompanion(context, prompt)
    }

    private fun callKiraForCompanion(context: Context, prompt: String): String {
        val apiKey = try {
            com.pr4nav.jarvis.llm.KiraClient.getApiKey(context)
        } catch (_: Exception) { "" }

        // Use the free Qwen model for companion messages (low cost, fast)
        val model = "qwen3.8-flash-free"
        val payload = JSONObject().apply {
            put("model", model)
            put("messages", JSONArray().apply {
                put(JSONObject().apply {
                    put("role", "user")
                    put("content", prompt)
                })
            })
            put("max_tokens", 60)
            put("temperature", 0.9)
        }

        val conn = URL("https://kiraai.vn/api/v1/chat/completions").openConnection() as HttpURLConnection
        return try {
            conn.apply {
                requestMethod = "POST"
                connectTimeout = 12_000
                readTimeout = 20_000
                doOutput = true
                setRequestProperty("Content-Type", "application/json")
                if (apiKey.isNotBlank()) setRequestProperty("Authorization", "Bearer $apiKey")
            }
            conn.outputStream.use { it.write(payload.toString().toByteArray()) }
            val code = conn.responseCode
            if (code !in 200..299) return ""
            val raw = conn.inputStream.bufferedReader().use { it.readText() }
            val resp = JSONObject(raw)
            val content = resp.optJSONArray("choices")
                ?.optJSONObject(0)
                ?.optJSONObject("message")
                ?.optString("content", "") ?: ""
            // Strip thinking tags
            content.replace(Regex("<think>[\\s\\S]*?</think>", RegexOption.IGNORE_CASE), "").trim()
        } catch (e: Exception) {
            Log.w(TAG, "Kira companion call failed: ${e.message}")
            ""
        } finally {
            conn.disconnect()
        }
    }

    // ── Notification ──────────────────────────────────────────────────────────

    private fun sendNotification(context: Context, message: String) {
        val nm = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel = NotificationChannel(
                CHANNEL_ID,
                "Jarvis Companion",
                NotificationManager.IMPORTANCE_DEFAULT
            ).apply {
                description = "Check-ins and proactive messages from Jarvis"
                setShowBadge(true)
            }
            nm.createNotificationChannel(channel)
        }

        val openIntent = Intent(context, AgentActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
            putExtra("auto_submit", message)
        }
        val pi = PendingIntent.getActivity(
            context, NOTIF_ID, openIntent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )

        val notif = NotificationCompat.Builder(context, CHANNEL_ID)
            .setSmallIcon(android.R.drawable.ic_dialog_info)
            .setContentTitle("Jarvis")
            .setContentText(message)
            .setStyle(NotificationCompat.BigTextStyle().bigText(message))
            .setContentIntent(pi)
            .setAutoCancel(true)
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .build()

        nm.notify(NOTIF_ID, notif)
        Log.i(TAG, "Proactive message sent: $message")
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private fun pendingIntent(context: Context): PendingIntent {
        val intent = Intent(context, ProactiveAlarmReceiver::class.java)
        return PendingIntent.getBroadcast(
            context, 8819, intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )
    }
}

/**
 * BroadcastReceiver that wakes up JarvisProactiveEngine when the alarm fires.
 * Also handles USER_PRESENT (device unlock) for opportunistic messages.
 */
class ProactiveAlarmReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        when (intent.action) {
            Intent.ACTION_USER_PRESENT -> {
                // On unlock: low-probability opportunistic message (10% chance, not counted in daily cap)
                if (JarvisProactiveEngine.isEnabled(context) && (1..10).random() == 1) {
                    JarvisProactiveEngine.onAlarmFired(context)
                }
            }
            else -> JarvisProactiveEngine.onAlarmFired(context)
        }
    }
}
